version: '3'
services:
        backtp2:
                image: kingsun21/front
                environment:
                        - ENVIRONMENT=dev
                #volumes:
                        #- logs
        fronttp2:
                image: kingsun21/back
                ports:
                        - "8081:8081"
                environment:
                        - APP_PORT=8081
                        - WS_BACK_URL=back
                links:
                        - "backtp2:back"
